'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated(),  _
     HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As ResourceManager
        
        Private resourceCulture As CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As ResourceManager = New ResourceManager("DoceusFungi.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bannerInvert() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bannerInvert", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bannerOrange() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bannerOrange", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BannerSmall() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BannerSmall", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property doceusfungi32() As Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("doceusfungi32", resourceCulture)
                Return CType(obj,Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Inifinity1() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inifinity1", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SoundOff() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoundOff", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SoundOn() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoundOn", resourceCulture)
                Return CType(obj,Bitmap)
            End Get
        End Property
    End Module
End Namespace
